### ISSUE TITLE
添加材质包后无法识别已修复的刷怪笼合成点的刷怪笼

### ISSUE THREAD

**Issue by jhqwqmc** [GuizhanCraft/ElectricSpawners-CN#5]
使用了材质包就无法合成
按照原理把item-models.yml文件里REINFORCED_SPAWNER的id改成0应该就能修复，但是建议从代码里修改成材质包的id

**Comment by ybw0014** [comment]
#3

**Comment by ybw0014** [comment]
粘液本体的合成系统有问题，之前尝试过但是合成出来的刷怪笼会完全一样
